name: tickler-cli
version: '0.0.0.0'
synopsis: A command line interface for the tickler app.
description: Please see README.md
category: Tickler
author: Tom Sydney Kerckhove & Nick Van den Broeck
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017-2018 Tom Sydney Kerckhove'
license: AllRightsReserved
github: NorfairKing/tickler-cli

library:
  source-dirs: src/
  ghc-options: -Wall
  default-extensions:
  - NoImplicitPrelude
  exposed-modules:
  - Tickler.Cli
  - Tickler.Cli.OptParse
  - Tickler.Cli.Session
  - Tickler.Cli.Store
  - Tickler.Cli.Sync

  dependencies:
  - aeson >=1.0
  - aeson-pretty >=0.8
  - base >=4.9 && <5
  - bytestring >=0.10
  - containers
  - cookie >=0.4
  - http-client >=0.5
  - http-client-tls >=0.3
  - mergeful
  - mtl >=2.2
  - optparse-applicative >=0.13
  - path >=0.4
  - path-io >=1.2
  - pretty-relative-time
  - servant >=0.9
  - servant-auth-client >=0.2
  - servant-auth-server >=0.3
  - servant-client >=0.9
  - tickler-api
  - tickler-client
  - tickler-data
  - servant-server >=0.9
  - validity
  - text >=1.2
  - time
  - yaml >=0.8
  - yamlparse-applicative

executables:
  tickler:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - tickler-cli

tests:
  tickler-cli-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - bytestring
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson >=0.1
    - sydtest
    - mergeful
    - mtl
    - path
    - path-io
    - servant
    - servant-client
    - text >=1.2
    - tickler-cli
    - tickler-client
    - tickler-data
    - tickler-server-gen
    - time
    - containers
