name: tickler-client

default-extensions:
- NoImplicitPrelude

library:
  source-dirs: src
  ghc-options: -Wall

  dependencies:
  - base >=4.7 && <5
  - bytestring >=0.10 && <0.11
  - containers
  - servant
  - servant-auth-client
  - servant-client
  - servant-flatten
  - text
  - tickler-api
  - tickler-data
  - time
  - typed-uuid
  - validity >=0.4
  - validity-bytestring >=0.2
  - validity-containers >=0.2
  - validity-text >=0.2
  - validity-time >=0.1
  - validity-uuid >=0.0
