name: tickler-client
version: '0.0.0.0'
synopsis: Tickler Client
category: Tickler
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016-2021 Tom Sydney Kerckhove'
license: AllRightsReserved
github: NorfairKing/tickler
default-extensions:
- NoImplicitPrelude
library:
  source-dirs: src
  ghc-options: -Wall

  dependencies:
  - base >=4.7 && <5
  - bytestring >=0.10 && <0.11
  - containers
  - servant
  - servant-auth-client
  - servant-client
  - servant-flatten
  - text
  - tickler-api
  - tickler-data
  - typed-uuid
  - validity >=0.4
  - validity-bytestring >=0.2
  - validity-containers >=0.2
  - validity-text >=0.2
  - validity-time >=0.1
  - validity-uuid >=0.0
