name: tickler-api
version: '0.0.0.0'
synopsis: Tickler API
category: Tickler
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016-2021 Tom Sydney Kerckhove'
license: AllRightsReserved
github: NorfairKing/tickler
default-extensions:
- NoImplicitPrelude

library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - aeson
  - base >=4.7 && <5
  - base64-bytestring
  - bytestring >=0.10 && <0.11
  - http-api-data
  - intray-api
  - intray-data
  - servant
  - servant-auth
  - servant-auth-server
  - stripe-core
  - text
  - tickler-data
  - time
  - typed-uuid
  - validity >=0.4
  - validity-aeson
  - validity-bytestring >=0.2
  - validity-text >=0.2
  - validity-time >=0.1
  - validity-uuid >=0.0
