extra-package-dbs: []
packages:
- tickler-api
- tickler-api-gen
- tickler-cli
- tickler-client
- tickler-client-gen
- tickler-data
- tickler-data-gen
- tickler-server
- tickler-server-test-utils
- tickler-web-server
- /home/syd/mergeless/mergeless
- /home/syd/mergeless/genvalidity-mergeless
- /home/syd/cs-syd/code/open-source/intray/intray-data-gen
- /home/syd/cs-syd/code/open-source/intray/intray-data
- /home/syd/cs-syd/code/open-source/intray/intray-api-gen
- /home/syd/cs-syd/code/open-source/intray/intray-api
- /home/syd/cs-syd/code/open-source/intray/intray-client
- /home/syd/cs-syd/code/open-source/intray/intray-server-test-utils
- /home/syd/cs-syd/code/open-source/intray/intray-server
extra-deps:
- hlint-2.0.15
- extra-1.6.5
- jose-0.6.0.3
- cookie-0.4.3
- servant-auth-0.3.1.0
- servant-auth-client-0.3.2.0
- servant-auth-docs-0.2.9.0
- servant-auth-server-0.3.2.0
- servant-flatten-0.2
- servant-options-0.1.0.0
- amazonka-1.6.0
- amazonka-core-1.6.0
- amazonka-ses-1.6.0
  # - git: git@github.com:NorfairKing/intray.git
  #   commit: a44433f29939af93959aa13e6362f5a369a14f55
  #   subdirs:
  #     - intray-data
  #     - intray-data-gen
  #     - intray-api
  #     - intray-api-gen
  #     - intray-client
  #     - intray-client-gen
  #     - intray-server
  #     - intray-server-test-utils
- git: git@github.com:NorfairKing/validity.git
  commit: a86dd3e4830c14c056a0d5d8712864d395d25b2a
  subdirs:
    - validity
    - validity-aeson
    - validity-bytestring
    - validity-containers
    - validity-path
    - validity-scientific
    - validity-text
    - validity-time
    - validity-unordered-containers
    - validity-uuid
    - validity-vector
    - genvalidity
    - genvalidity-aeson
    - genvalidity-bytestring
    - genvalidity-containers
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-path
    - genvalidity-property
    - genvalidity-scientific
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - genvalidity-uuid
    - genvalidity-vector
- git: https://github.com/NorfairKing/typed-uuid.git
  commit: 155c9ec880ca1c12f7dd8a8468b3626de8164823
  subdirs:
    - typed-uuid
    - genvalidity-typed-uuid
- git: git@github.com:NorfairKing/pretty-relative-time.git
  commit: 9a670db25ac68974045c75da364486c10970824f
resolver: lts-11.9
