resolver: lts-14.20
packages:
- tickler-api
- tickler-api-gen
- tickler-cli
- tickler-client
- tickler-client-gen
- tickler-data
- tickler-data-gen
- tickler-server
- tickler-server-test-utils
- tickler-web-server
extra-deps:
- amazonka-1.6.1
- amazonka-core-1.6.1
- amazonka-ses-1.6.1
- servant-auth-client-0.4.0.0@sha256:68879b7f44d87f73ef68c7bb21006167f5623c4cd6a2a3fce4d5ea3959a8c730,3426
- servant-flatten-0.2@sha256:276896f7c5cdec5b8f8493f6205fded0cc602d050b58fdb09a6d7c85c3bb0837,1234

- github: NorfairKing/looper
  commit: 929a8ad6a99a84624767bd9d619cc5318c6bda56

- github: NorfairKing/yesod-static-remote
  commit: 22c0a92c1d62f1b8d432003844ef0636a9131b08

- github: NorfairKing/stripe
  commit: 7ced8cef1e932d3fb222dfb3c79c25595cdc82ab
  subdirs:
    - stripe-core
    - stripe-haskell
    - stripe-http-client
    - stripe-http-streams

- github: NorfairKing/intray
  commit: fbe9968eec15fdab271b12ea11e140084ea75f13
  subdirs:
    - intray-data
    - intray-data-gen
    - intray-api
    - intray-api-gen
    - intray-client
    - intray-server
    - intray-server-test-utils

- github: NorfairKing/mergeless
  commit: 3d5f4b54cc2c4c8c6f33a716bc6b67f376b8d1d5
  subdirs:
    - mergeless
    - genvalidity-mergeless

- github: NorfairKing/validity
  commit: 165c75d350460c0f936600b17795ba40b298786b
  subdirs:
    - validity
    - validity-aeson
    - validity-bytestring
    - validity-containers
    - validity-path
    - validity-scientific
    - validity-text
    - validity-time
    - validity-unordered-containers
    - validity-uuid
    - validity-vector
    - genvalidity
    - genvalidity-aeson
    - genvalidity-bytestring
    - genvalidity-containers
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-path
    - genvalidity-property
    - genvalidity-scientific
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - genvalidity-uuid
    - genvalidity-vector

- github: NorfairKing/typed-uuid
  commit: 4c5739c5e231b1cee6bd568ec55734116691ac8f
  subdirs:
    - typed-uuid
    - genvalidity-typed-uuid

- github: NorfairKing/pretty-relative-time
  commit: 2abdb2ba83ad47b8369e2ef618c7c21b82d80b23

nix:
  packages: [zlib]
