resolver: lts-18.16
packages:
- tickler-api
- tickler-api-gen
- tickler-client
- tickler-data
- tickler-data-gen
- tickler-server
- tickler-server-gen
- tickler-web-server
- tickler-web-server-gen
- tickler-web-server-webdriver

- stripe-client # Intray
- tickler-stripe-client

# These are duplicated in nix/overlay.nix 
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef
  tickler-stripe-client: -w # Turn off warnings for the generated code.
  stripe-client: -w # Turn off warnings for the generated code.

extra-deps:
- amazonka-1.6.1@sha256:f58b63e83876f93aa03c54e54b3eb8ba9358af93819d41f4a5a8f8b7d8b8399c,3544
- unliftio-core-0.1.2.0@sha256:b0a7652ffce2284a6cebe05c99eb60573a8fb6631163f34b0b30a80b4a78cb23,1081

- servant-flatten-0.2@sha256:276896f7c5cdec5b8f8493f6205fded0cc602d050b58fdb09a6d7c85c3bb0837,1234
- envparse-0.4.1@sha256:989902e6368532548f61de1fa245ad2b39176cddd8743b20071af519a709ce30,2842

- github: NorfairKing/yesod-static-remote
  commit: 22c0a92c1d62f1b8d432003844ef0636a9131b08

- github: NorfairKing/intray
  commit: 98e3dad0c1ff7b5ef8c1db636b02511148c51198
  subdirs:
    - intray-data
    - intray-data-gen
    - intray-api
    - intray-api-gen
    - intray-client
    - intray-server
    - intray-server-gen
      
- github: NorfairKing/mergeless
  commit: 9a10547aba61f10a32ba2a54dbe7301ced48f9fc
  subdirs:
    - mergeless
    - mergeless-persistent
    - genvalidity-mergeless

- github: NorfairKing/validity
  commit: e1750f9d29c64705a4b9ccddf9f5afd5275e7d75
  subdirs:
    - genvalidity
    - genvalidity-aeson
    - genvalidity-bytestring
    - genvalidity-containers
    - genvalidity-criterion
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-hspec-binary
    - genvalidity-hspec-cereal
    - genvalidity-hspec-hashable
    - genvalidity-hspec-optics
    - genvalidity-hspec-persistent
    - genvalidity-path
    - genvalidity-persistent
    - genvalidity-property
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-sydtest-hashable
    - genvalidity-sydtest-persistent
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - genvalidity-uuid
    - genvalidity-vector
    - validity
    - validity-aeson
    - validity-bytestring
    - validity-containers
    - validity-path
    - validity-persistent
    - validity-primitive
    - validity-scientific
    - validity-text
    - validity-time
    - validity-unordered-containers
    - validity-uuid
    - validity-vector

- github: NorfairKing/typed-uuid
  commit: 00fbc7e0380ab2ff72e8fd02323e76f13b7d5b59
  subdirs:
    - typed-uuid
    - genvalidity-typed-uuid

- github: NorfairKing/pretty-relative-time
  commit: a634358ff274380a12360f7814c3aea46ea35b1b

- github: NorfairKing/safe-coloured-text
  commit: f30fe0e4d2a0fa036967ffe17538b60e5f9861f5
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo

- github: NorfairKing/looper
  commit: 6f7d44f563a7e21c3ca5fa24ebe01ed1665426ca
  subdirs:
    - looper

- github: NorfairKing/sydtest
  commit: e55fad0f6b8058a9b44c6c0d66bdd3c3be556d71
  subdirs:
  - sydtest
  - sydtest-discover
  - sydtest-persistent
  - sydtest-persistent-sqlite
  - sydtest-typed-process
  - sydtest-wai
  - sydtest-webdriver
  - sydtest-webdriver-screenshot
  - sydtest-webdriver-yesod
  - sydtest-yesod

- github: NorfairKing/autodocodec
  commit: f0cb2ead0985b4394db0627e6befd7ce23c54c22
  subdirs:
  - autodocodec
  - autodocodec-yaml
  - autodocodec-schema

- github: NorfairKing/yesod-autoreload
  commit: 7135e864c0d4a48efeae473ee2761f5168946e58

nix:
  shell-file: shell.nix
