resolver: lts-14.23
packages:
- tickler-api
- tickler-api-gen
- tickler-cli
- tickler-client
- tickler-client-gen
- tickler-data
- tickler-data-gen
- tickler-server
- tickler-server-gen
- tickler-web-server
extra-deps:
- amazonka-1.6.1
- amazonka-core-1.6.1
- amazonka-ses-1.6.1
- servant-auth-client-0.4.0.0@sha256:68879b7f44d87f73ef68c7bb21006167f5623c4cd6a2a3fce4d5ea3959a8c730,3426
- servant-flatten-0.2@sha256:276896f7c5cdec5b8f8493f6205fded0cc602d050b58fdb09a6d7c85c3bb0837,1234

- github: NorfairKing/yesod-static-remote
  commit: 22c0a92c1d62f1b8d432003844ef0636a9131b08

- github: NorfairKing/stripe
  commit: 7ced8cef1e932d3fb222dfb3c79c25595cdc82ab
  subdirs:
    - stripe-core
    - stripe-haskell
    - stripe-http-client
    - stripe-http-streams

- github: NorfairKing/intray
  commit: 679617d7c8203299c0094a43049da30a7a09f1ba
  subdirs:
    - intray-data
    - intray-data-gen
    - intray-api
    - intray-api-gen
    - intray-client
    - intray-server
    - intray-server-gen

- github: NorfairKing/mergeless
  commit: 32fb75445723213ed78f678c20a2271a48e5dd41
  subdirs:
    - mergeless
    - genvalidity-mergeless

- github: NorfairKing/mergeful
  commit: 4e3cf189c76d04daf9c26267a64523ec8bb071aa
  subdirs:
    - mergeful
    - genvalidity-mergeful

- github: NorfairKing/validity
  commit: ac28a5c0fc8559f96ffe7f9286ffff1b879a39f3
  subdirs:
    - validity
    - validity-aeson
    - validity-bytestring
    - validity-containers
    - validity-path
    - validity-scientific
    - validity-text
    - validity-time
    - validity-unordered-containers
    - validity-uuid
    - validity-vector
    - genvalidity
    - genvalidity-aeson
    - genvalidity-bytestring
    - genvalidity-containers
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-hspec-persistent
    - genvalidity-path
    - genvalidity-property
    - genvalidity-scientific
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - genvalidity-uuid
    - genvalidity-vector

- github: NorfairKing/typed-uuid
  commit: dbc8fd4b56b78b1f9cf00bc2890d43dc19b97c5c
  subdirs:
    - typed-uuid
    - genvalidity-typed-uuid

- github: NorfairKing/pretty-relative-time
  commit: 4eb01d55ef8f0f37fa63093be3ec67e99df4962f
- github: NorfairKing/looper
  commit: 929a8ad6a99a84624767bd9d619cc5318c6bda56

nix:
  path: [ "nixpkgs=https://github.com/NixOS/nixpkgs/archive/323fe92057bb38475a446ff5e18d3b388c2e4403.tar.gz" ]
  add-gc-roots: true
  pure: true
  packages:
  - zlib
  - unzip
  - haskellPackages.autoexporter
  - procps
  - killall
