resolver: lts-18.16
packages:
- tickler-api
- tickler-api-gen
- tickler-client
- tickler-data
- tickler-data-gen
- tickler-server
- tickler-server-gen
- tickler-web-server
- tickler-web-server-gen
- tickler-web-server-webdriver

- intray-stripe-client
- tickler-stripe-client

# These are duplicated in nix/overlay.nix 
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef
  intray-stripe-client: -w # Turn off warnings for the generated code.
  tickler-stripe-client: -w # Turn off warnings for the generated code.

extra-deps:
- amazonka-1.6.1@sha256:f58b63e83876f93aa03c54e54b3eb8ba9358af93819d41f4a5a8f8b7d8b8399c,3544
- unliftio-core-0.1.2.0@sha256:b0a7652ffce2284a6cebe05c99eb60573a8fb6631163f34b0b30a80b4a78cb23,1081

- servant-flatten-0.2@sha256:276896f7c5cdec5b8f8493f6205fded0cc602d050b58fdb09a6d7c85c3bb0837,1234
- envparse-0.4.1@sha256:989902e6368532548f61de1fa245ad2b39176cddd8743b20071af519a709ce30,2842


- github: NorfairKing/intray
  commit: be749bd66a5d9859826b4854bf9d1da5f15e3517
  subdirs:
    - intray-data
    - intray-data-gen
    - intray-api
    - intray-api-gen
    - intray-client
    - intray-server
    - intray-server-gen
      
- github: NorfairKing/mergeless
  commit: 639cdca0dc7cce53a62cf40aa856b156e2ab1f32
  subdirs:
    - mergeless
    - mergeless-persistent
    - genvalidity-mergeless

- github: NorfairKing/validity
  commit: 160e846cc5de8e92e6758172da341f5d81fe037
  subdirs:
    - genvalidity
    - genvalidity-aeson
    - genvalidity-bytestring
    - genvalidity-containers
    - genvalidity-criterion
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-hspec-binary
    - genvalidity-hspec-cereal
    - genvalidity-hspec-hashable
    - genvalidity-hspec-optics
    - genvalidity-hspec-persistent
    - genvalidity-path
    - genvalidity-persistent
    - genvalidity-property
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-sydtest-hashable
    - genvalidity-sydtest-persistent
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - genvalidity-uuid
    - genvalidity-vector
    - validity
    - validity-aeson
    - validity-bytestring
    - validity-containers
    - validity-path
    - validity-persistent
    - validity-primitive
    - validity-scientific
    - validity-text
    - validity-time
    - validity-unordered-containers
    - validity-uuid
    - validity-vector

- github: NorfairKing/typed-uuid
  commit: 00fbc7e0380ab2ff72e8fd02323e76f13b7d5b59
  subdirs:
    - typed-uuid
    - genvalidity-typed-uuid

- github: NorfairKing/pretty-relative-time
  commit: a634358ff274380a12360f7814c3aea46ea35b1b

- github: NorfairKing/safe-coloured-text
  commit: 71c5940a3b84eeb498304d8e584e7638f875d51b
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo

- github: NorfairKing/looper
  commit: 6f7d44f563a7e21c3ca5fa24ebe01ed1665426ca
  subdirs:
    - looper

- github: NorfairKing/sydtest
  commit: 7e30853ff89503968165d4ebb9c3d42f005a1975
  subdirs:
  - sydtest
  - sydtest-aeson
  - sydtest-discover
  - sydtest-persistent
  - sydtest-persistent-sqlite
  - sydtest-typed-process
  - sydtest-wai
  - sydtest-webdriver
  - sydtest-webdriver-screenshot
  - sydtest-webdriver-yesod
  - sydtest-yesod

- github: NorfairKing/autodocodec
  commit: 38bd4865ff2dd40d342141b7fde9319f835d98c6
  subdirs:
  - autodocodec
  - autodocodec-yaml
  - autodocodec-schema

- github: NorfairKing/yesod-static-remote
  commit: ed6bf8ef434d49b160429028613a1f6882fccfdf

- github: NorfairKing/yesod-autoreload
  commit: 7135e864c0d4a48efeae473ee2761f5168946e58

nix:
  shell-file: shell.nix
