extra-package-dbs: []
packages:
- tickler-api
- tickler-api-gen
- tickler-cli
- tickler-client
- tickler-client-gen
- tickler-data
- tickler-data-gen
- tickler-server
- tickler-server-test-utils
- tickler-web-server
extra-deps:
- hlint-2.0.15
- extra-1.6.5
- jose-0.6.0.3
- cookie-0.4.3
- servant-auth-0.3.1.0
- servant-auth-client-0.3.2.0
- servant-auth-docs-0.2.9.0
- servant-auth-server-0.3.2.0
- servant-flatten-0.2
- servant-options-0.1.0.0
- amazonka-1.6.0
- amazonka-core-1.6.0
- amazonka-ses-1.6.0
- git: git@github.com:NorfairKing/intray.git
  commit: d6a5e1143ebf073742f1d2fc135b746b17f21d45
  subdirs:
    - intray-data
    - intray-data-gen
    - intray-api
    - intray-api-gen
    - intray-client
    - intray-server
    - intray-server-test-utils
- git: https://github.com/NorfairKing/mergeless.git
  commit: 0198f9393e2ef71f26de6427541387be44fd499b
  subdirs:
    - mergeless
    - genvalidity-mergeless
- git: git@github.com:NorfairKing/validity.git
  commit: d128cc30bc886e31ea7f8161fb7708c08b162937
  subdirs:
    - validity
    - validity-aeson
    - validity-bytestring
    - validity-containers
    - validity-path
    - validity-scientific
    - validity-text
    - validity-time
    - validity-unordered-containers
    - validity-uuid
    - validity-vector
    - genvalidity
    - genvalidity-aeson
    - genvalidity-bytestring
    - genvalidity-containers
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-path
    - genvalidity-property
    - genvalidity-scientific
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - genvalidity-uuid
    - genvalidity-vector
- git: https://github.com/NorfairKing/typed-uuid.git
  commit: 155c9ec880ca1c12f7dd8a8468b3626de8164823
  subdirs:
    - typed-uuid
    - genvalidity-typed-uuid
- git: git@github.com:NorfairKing/pretty-relative-time.git
  commit: 21b29c9d729ed91a56819f569de6fdc8582d7e3d
resolver: lts-11.9
nix:
  packages: [zlib]
