resolver: lts-20.23
packages:
- tickler-api
- tickler-api-gen
- tickler-client
- tickler-data
- tickler-data-gen
- tickler-server
- tickler-server-gen
- tickler-web-server
- tickler-web-server-gen
- tickler-web-server-webdriver

- intray-stripe-client
- tickler-stripe-client

# These are duplicated in nix/overlay.nix 
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef
  intray-stripe-client: -w # Turn off warnings for the generated code.
  tickler-stripe-client: -w # Turn off warnings for the generated code.

extra-deps:

- github: NorfairKing/intray
  commit: e39177c80b56d3519649bef695763c7afd44ee96
  subdirs:
    - intray-api
    - intray-api-gen
    - intray-cli-data
    - intray-client
    - intray-data
    - intray-data-gen
    - intray-server
    - intray-server-gen
      
- github: NorfairKing/mergeless
  commit: b6bfcca1ae17e5ac662c6aa9128ed0b293b1f9c8
  subdirs:
    - mergeless
    - mergeless-persistent
    - genvalidity-mergeless

- github: NorfairKing/typed-uuid
  commit: 00fbc7e0380ab2ff72e8fd02323e76f13b7d5b59
  subdirs:
    - typed-uuid
    - genvalidity-typed-uuid

- github: NorfairKing/pretty-relative-time
  commit: a634358ff274380a12360f7814c3aea46ea35b1b

- github: NorfairKing/looper
  commit: fd36d37becfa04fa4d7e00604e37c61817b6b62b
  subdirs:
    - looper

- github: NorfairKing/yesod-static-remote
  commit: 7eda644dc369e16c3591847f6c7cad30846bf6b0

- github: NorfairKing/yesod-autoreload
  commit: 796def9af50cd7b053c9fb4a065c55603d4a8399

- github: georgefst/hs-webdriver
  commit: cf9c387de7c1525ffbcd58125ccb3f798a97a2bb

- github: brendanhay/amazonka
  commit: 2dc498fe75ff47db2db3ee63e042b1aa3da57c0f
  subdirs:
  - lib/amazonka
  - lib/amazonka-core
  - lib/amazonka-test
  - lib/services/amazonka-ses
  - lib/services/amazonka-sso
  - lib/services/amazonka-sts

- github: NorfairKing/sydtest
  commit: dcd230e48f164594a473925fa0dbbaf956eb6848
  subdirs:
    - sydtest
    - sydtest-aeson
    - sydtest-discover
    - sydtest-persistent
    - sydtest-persistent-sqlite
    - sydtest-servant
    - sydtest-wai
    - sydtest-webdriver
    - sydtest-webdriver-yesod
    - sydtest-yesod

system-ghc: true
nix:
  enable: false
with-hpack: hpack
