resolver: lts-19.32
packages:
- tickler-api
- tickler-api-gen
- tickler-client
- tickler-data
- tickler-data-gen
- tickler-server
- tickler-server-gen
- tickler-web-server
- tickler-web-server-gen
- tickler-web-server-webdriver

- intray-stripe-client
- tickler-stripe-client

# These are duplicated in nix/overlay.nix 
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef
  intray-stripe-client: -w # Turn off warnings for the generated code.
  tickler-stripe-client: -w # Turn off warnings for the generated code.

extra-deps:

- github: NorfairKing/intray
  commit: 1464e7a1c4f7fe7f05afc900859517dc54269ed9
  subdirs:
    - intray-api
    - intray-api-gen
    - intray-cli-data
    - intray-client
    - intray-data
    - intray-data-gen
    - intray-server
    - intray-server-gen
      
- github: NorfairKing/mergeless
  commit: b6bfcca1ae17e5ac662c6aa9128ed0b293b1f9c8
  subdirs:
    - mergeless
    - mergeless-persistent
    - genvalidity-mergeless

- github: NorfairKing/validity
  commit: 2e9198bdaaa8c80a5dbe2b7b860b5c26558c6374
  subdirs:
    - genvalidity
    - genvalidity-aeson
    - genvalidity-bytestring
    - genvalidity-containers
    - genvalidity-criterion
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-hspec-binary
    - genvalidity-hspec-cereal
    - genvalidity-hspec-hashable
    - genvalidity-hspec-optics
    - genvalidity-hspec-persistent
    - genvalidity-path
    - genvalidity-persistent
    - genvalidity-property
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-sydtest-hashable
    - genvalidity-sydtest-persistent
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - genvalidity-uuid
    - genvalidity-vector
    - validity
    - validity-aeson
    - validity-bytestring
    - validity-containers
    - validity-path
    - validity-persistent
    - validity-primitive
    - validity-scientific
    - validity-text
    - validity-time
    - validity-unordered-containers
    - validity-uuid
    - validity-vector

- github: NorfairKing/typed-uuid
  commit: 00fbc7e0380ab2ff72e8fd02323e76f13b7d5b59
  subdirs:
    - typed-uuid
    - genvalidity-typed-uuid

- github: NorfairKing/pretty-relative-time
  commit: a634358ff274380a12360f7814c3aea46ea35b1b

- github: NorfairKing/safe-coloured-text
  commit: 675cb01fce5f46718416d7746de5b856ed90a63f
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo

- github: NorfairKing/looper
  commit: fd36d37becfa04fa4d7e00604e37c61817b6b62b
  subdirs:
    - looper

- github: NorfairKing/sydtest
  commit: ff224861ea409a9ee08576adb0438bbbb948917f
  subdirs:
  - sydtest
  - sydtest-aeson
  - sydtest-discover
  - sydtest-persistent
  - sydtest-persistent-sqlite
  - sydtest-typed-process
  - sydtest-wai
  - sydtest-webdriver
  - sydtest-webdriver-screenshot
  - sydtest-webdriver-yesod
  - sydtest-yesod

- github: NorfairKing/autodocodec
  commit: e337d681109cac273f5b9ea2b54b174bce79d312
  subdirs:
  - autodocodec
  - autodocodec-yaml
  - autodocodec-schema

- github: NorfairKing/yesod-static-remote
  commit: 7eda644dc369e16c3591847f6c7cad30846bf6b0

- github: NorfairKing/yesod-autoreload
  commit: 796def9af50cd7b053c9fb4a065c55603d4a8399

- github: georgefst/hs-webdriver
  commit: cf9c387de7c1525ffbcd58125ccb3f798a97a2bb

- github: brendanhay/amazonka
  commit: cfe2584aef0b03c86650372d362c74f237925d8c
  subdirs:
  - lib/amazonka
  - lib/amazonka-core
  - lib/amazonka-test
  - lib/services/amazonka-ses
  - lib/services/amazonka-sso
  - lib/services/amazonka-sts

system-ghc: true
nix:
  enable: false
with-hpack: hpack
