name: tickler-server
version: '0.0.0.0'
synopsis: Tickler Server
description: Please see README.md
category: Tickler
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016-2018 Tom Sydney Kerckhove'
license: AllRightsReserved
github: NorfairKing/tickler-server

library:
  source-dirs: src
  ghc-options: -Wall
  default-extensions:
  - NoImplicitPrelude
  exposed-modules:
  - TicklerServer
  - Tickler.Server
  - Tickler.Server.Handler.PostSync
  - Tickler.Server.Handler.Utils
  - Tickler.Server.Looper
  - Tickler.Server.Looper.Triggerer
  - Tickler.Server.OptParse
  - Tickler.Server.OptParse.Types
  - Tickler.Server.Types

  dependencies:
  - aeson
  - aeson-pretty
  - amazonka
  - amazonka-ses
  - async
  - base >=4.7 && <5
  - blaze-html
  - bytestring
  - containers
  - cookie
  - data-default
  - email-validate
  - exceptions
  - file-embed
  - http-client
  - http-client-tls
  - http-types
  - intray-client
  - jose
  - lens
  - markdown
  - mergeless
  - monad-logger
  - mtl >=2.2
  - nonce
  - optparse-applicative >=0.13
  - path
  - path-io
  - persistent
  - persistent-sqlite
  - persistent-template
  - pretty-show
  - resource-pool
  - resourcet
  - retry
  - safe
  - servant
  - servant-auth-server
  - servant-auth-client
  - servant-client
  - servant-client-core
  - servant-docs
  - servant-generic
  - servant-server
  - shakespeare
  - template-haskell
  - text
  - tickler-api
  - tickler-client
  - tickler-data
  - time
  - typed-uuid
  - validity
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-text
  - validity-time
  - wai
  - wai-app-static
  - wai-cors
  - wai-extra
  - warp >=3.2
  - yaml

executables:
  tickler-server:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - tickler-server
