name: tickler-server

extra-source-files:
- templates/**/*

dependencies:
- base

library:
  source-dirs: src
  ghc-options: -Wall
  default-extensions:
  - NoImplicitPrelude

  dependencies:
  - aeson
  - aeson-pretty
  - amazonka
  - amazonka-ses
  - async
  - autodocodec
  - autodocodec-yaml
  - blaze-html
  - bytestring
  - cache
  - conduit
  - cookie
  - envparse
  - esqueleto
  - exceptions
  - http-client
  - http-client-tls
  - intray-client
  - intray-server # Only for Web.Stripe.Conduit
  - jose
  - lens
  - looper
  - monad-logger
  - mtl >=2.2
  - optparse-applicative >=0.13
  - path
  - path-io
  - persistent
  - persistent-sqlite
  - pretty-show
  - resource-pool
  - resourcet
  - retry
  - servant
  - servant-auth-client
  - servant-auth-server
  - servant-client
  - servant-server
  - shakespeare
  - text
  - tickler-api
  - tickler-client
  - tickler-data
  - tickler-stripe-client
  - time
  - typed-uuid
  - unliftio
  - unordered-containers
  - wai
  - wai-cors
  - warp >=3.2

executables:
  tickler-server:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - tickler-server

# For coverage reports, until this issue is fixed:
# https://github.com/commercialhaskell/stack/issues/5713
tests:
  tickler-server-dummy:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tickler-server

