name: tickler-web-server-webdriver

dependencies:
- base >= 4.9 && < 5

library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - containers
  - http-client
  - intray-client
  - mtl
  - persistent
  - servant-auth-client
  - sydtest
  - sydtest-webdriver
  - sydtest-webdriver-yesod
  - sydtest-yesod
  - text
  - tickler-api
  - tickler-client
  - tickler-server-gen
  - tickler-web-server
  - tickler-web-server-gen
  - time
  - unordered-containers
  - webdriver

tests:
  tickler-web-server-webdriver-test:
    main: Main.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - containers
    - genvalidity-sydtest
    - http-client
    - http-types
    - intray-client
    - intray-server-gen
    - mtl
    - persistent
    - sydtest
    - sydtest-webdriver
    - sydtest-webdriver-yesod
    - sydtest-yesod
    - text
    - tickler-api
    - tickler-client
    - tickler-server-gen
    - tickler-web-server
    - tickler-web-server-gen
    - tickler-web-server-webdriver
    - time
    - webdriver
