name:    tickler-web-server-webdriver
version: "0.0.0.0"

dependencies:
- base >= 4.9 && < 5

library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - mtl
  - sydtest
  - sydtest-webdriver
  - sydtest-webdriver-yesod
  - text
  - tickler-api
  - tickler-client
  - tickler-server-gen
  - tickler-web-server
  - tickler-web-server-gen
  - time
  - webdriver
  - unordered-containers
  - servant-auth-client

tests:
  tickler-web-server-webdriver-test:
    main: Main.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - genvalidity-sydtest
    - sydtest
    - sydtest-webdriver
    - sydtest-webdriver-yesod
    - tickler-api
    - tickler-client
    - tickler-server-gen
    - tickler-web-server
    - tickler-web-server-gen
    - tickler-web-server-webdriver
    - time
