name:    tickler-web-server
version: "0.0.0.0"

library:
  source-dirs: src
  ghc-options: -Wall
  default-extensions: NoImplicitPrelude

  dependencies:
  - aeson
  - aeson-pretty
  - amazonka
  - async
  - base >=4.9 && <5
  - base16-bytestring
  - bytestring
  - containers
  - cookie
  - data-default
  - http-client
  - http-client-tls
  - http-media
  - http-types
  - intray-data
  - lens
  - mtl
  - optparse-applicative >=0.13 && <0.15
  - path
  - path-io
  - persistent-sqlite
  - pretty-relative-time
  - pretty-show
  - servant
  - tickler-api
  - tickler-client
  - tickler-data
  - tickler-server
  - servant-auth-client
  - servant-client
  - servant-client-core
  - shakespeare
  - template-haskell
  - text
  - time
  - transformers
  - typed-uuid
  - unordered-containers
  - wai
  - yesod
  - yesod-auth
  - yesod-core
  - yesod-form
  - yesod-static

executables:
  tickler-web-server:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >=4.9 && <5
    - tickler-web-server

tests:
  tickler-web-server-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - base >=4.9 && <5
    - genvalidity-hspec
    - hspec
    - hspec-core
    - http-types
    - lens
    - mtl
    - path
    - path-io
    - persistent-sqlite
    - pretty-show
    - servant-client
    - text
    - tickler-data
    - tickler-data-gen
    - tickler-server
    - tickler-server-test-utils
    - tickler-web-server
    - typed-uuid
    - yesod-auth
    - yesod-test
