name:    tickler-web-server
version: "0.0.0.0"

extra-source-files:
- routes
- static/*.jpg
- static/*.ico
- static/*.svg
- templates/**/*

dependencies:
- base >= 4.9 && < 5

library:
  source-dirs: src
  ghc-options: -Wall
  default-extensions: NoImplicitPrelude

  dependencies:
  - aeson
  - aeson-pretty
  - autodocodec
  - autodocodec-yaml
  - base16-bytestring
  - bytestring
  - cookie
  - data-default
  - http-client
  - http-client-tls
  - http-types
  - intray-data
  - mtl
  - optparse-applicative
  - path
  - path-io
  - pretty-relative-time
  - pretty-show
  - servant
  - servant-auth-client
  - servant-client
  - servant-client-core
  - shakespeare
  - stripe-core
  - stripe-haskell
  - template-haskell
  - text
  - tickler-api
  - tickler-client
  - tickler-data
  - tickler-server
  - time
  - transformers
  - typed-uuid
  - unordered-containers
  - yesod
  - yesod-auth
  - yesod-autoreload
  - yesod-static
  - yesod-static-remote

executables:
  tickler-web-server:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tickler-web-server

tests:
  tickler-web-server-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - genvalidity-sydtest
    - http-client
    - http-types
    - mtl
    - path
    - path-io
    - pretty-show
    - servant-client
    - sydtest
    - sydtest-yesod
    - text
    - tickler-client
    - tickler-data
    - tickler-data-gen
    - tickler-server
    - tickler-server-gen
    - tickler-web-server
    - time
    - typed-uuid
    - yesod-auth

  tickler-web-server-webdriver-test:
    main: Main.hs
    source-dirs: webdriver-test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sydtest
    - sydtest-webdriver
    - sydtest-webdriver-yesod
    - tickler-web-server
