name: tickler-client-gen
version: '0.0.0.0'
synopsis: Tickler Client Generators
category: Tickler
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016-2018 Tom Sydney Kerckhove'
license: AllRightsReserved
github: NorfairKing/tickler
default-extensions:
- NoImplicitPrelude

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Tickler.Client.Gen
  
  dependencies:
  - QuickCheck
  - base >=4.7 && <5
  - genvalidity
  - genvalidity-containers
  - tickler-client
  - tickler-api-gen

tests:
  tickler-client-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - base
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - hspec
    - tickler-api
    - tickler-client
    - tickler-client-gen
    - tickler-data-gen
    - text
