name: tickler-server-gen

extra-source-files:
- test_resources/**/*

library:
  source-dirs: src
  ghc-options: -Wall
  default-extensions:
  - NoImplicitPrelude

  dependencies:
  - QuickCheck >=2.9
  - aeson
  - base
  - bytestring >=0.10
  - cache
  - cookie >=0.4 && <0.5
  - genvalidity-bytestring
  - genvalidity-sydtest
  - genvalidity-text
  - genvalidity-time
  - http-client
  - http-types
  - intray-server
  - intray-server-gen
  - monad-logger
  - path
  - path-io
  - persistent-sqlite
  - servant
  - servant-auth-client
  - servant-auth-server
  - servant-client
  - servant-server
  - sydtest
  - sydtest-persistent-sqlite
  - sydtest-wai
  - text >=1.2 && <1.3
  - tickler-api
  - tickler-api-gen
  - tickler-client
  - tickler-data
  - tickler-data-gen
  - tickler-server
  - time
  - typed-uuid

benchmarks:
  tickler-server-bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fno-warn-name-shadowing
    dependencies:
    - QuickCheck
    - base
    - bytestring
    - cookie
    - criterion
    - http-client
    - servant
    - servant-auth-client
    - servant-client
    - sydtest
    - tickler-client
    - tickler-server-gen

tests:
  tickler-server-test:
    main: Spec.hs
    source-dirs: test
    default-extensions:
    - NoImplicitPrelude
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - aeson
    - base >=4.9 && <5
    - bytestring
    - containers
    - genvalidity-bytestring
    - genvalidity-sydtest
    - genvalidity-text
    - genvalidity-time
    - http-types
    - intray-client
    - intray-server-gen
    - monad-logger
    - path
    - path-io
    - persistent
    - servant
    - servant-client
    - sydtest
    - sydtest-aeson
    - sydtest-persistent
    - text
    - tickler-api
    - tickler-api-gen
    - tickler-client
    - tickler-data
    - tickler-data-gen
    - tickler-server
    - tickler-server-gen
    - tickler-stripe-client
    - time
    - typed-uuid
    - unordered-containers
    - uuid
