name: tickler-server-gen
version: '0.0.0.0'
synopsis: Test utils for tickler-server
description: Please see README.md
category: Tickler
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016-2021 Tom Sydney Kerckhove'
license: AllRightsReserved
github: NorfairKing/tickler-server

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Tickler.Server.TestUtils
  default-extensions:
  - NoImplicitPrelude

  dependencies:
  - QuickCheck >=2.9
  - base
  - bytestring >=0.10 && <0.11
  - cache
  - cookie >=0.4 && <0.5
  - genvalidity-bytestring
  - genvalidity-sydtest
  - genvalidity-text
  - genvalidity-time
  - http-client
  - http-types
  - intray-server
  - intray-server-gen
  - path
  - path-io
  - persistent-sqlite
  - servant
  - servant-auth-client
  - servant-auth-server
  - servant-client
  - servant-server
  - stripe-core
  - sydtest
  - sydtest-persistent-sqlite
  - sydtest-wai
  - text >=1.2 && <1.3
  - tickler-api
  - tickler-api-gen
  - tickler-client
  - tickler-data
  - tickler-data-gen
  - tickler-server
  - time
  - typed-uuid

tests:
  tickler-server-test:
    main: Spec.hs
    source-dirs: test
    default-extensions:
    - NoImplicitPrelude
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >=4.9 && <5
    - QuickCheck
    - bytestring
    - containers
    - genvalidity-bytestring
    - genvalidity-sydtest
    - genvalidity-text
    - genvalidity-time
    - sydtest
    - http-types
    - intray-client
    - intray-server-gen
    - path
    - path-io
    - servant
    - servant-client
    - text
    - tickler-api
    - tickler-api-gen
    - tickler-client
    - tickler-data
    - tickler-data-gen
    - tickler-server
    - tickler-server-gen
    - time

benchmarks:
  tickler-server-bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fno-warn-name-shadowing
    dependencies:
    - QuickCheck
    - base
    - bytestring
    - cookie
    - criterion
    - http-client
    - servant
    - servant-auth-client
    - servant-client
    - sydtest
    - tickler-client
    - tickler-server-gen
