name: tickler-data-gen
version: '0.0.0.0'
synopsis: Generators for tickler-data
category: Tickler
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017-2018 Tom Sydney Kerckhove'
license: AllRightsReserved
github: NorfairKing/tickler-server
default-extensions:
- NoImplicitPrelude

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Tickler.Data.Gen

  dependencies:
  - QuickCheck
  - base >=4.7 && <5
  - bytestring
  - genvalidity
  - genvalidity-bytestring
  - genvalidity-mergeful
  - genvalidity-persistent
  - genvalidity-text
  - genvalidity-time
  - genvalidity-typed-uuid
  - genvalidity-uuid
  - intray-api-gen
  - persistent
  - servant-client-core
  - text
  - tickler-data
  - validity
  - validity-bytestring
  - validity-text
  - validity-time

tests:
  tickler-data-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - base
    - bytestring
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-hspec-persistent
    - genvalidity-text
    - hspec
    - intray-data
    - mergeful
    - text
    - tickler-data
    - tickler-data-gen
