name: tickler-api-gen
version: '0.0.0.0'
synopsis: Generators for tickler-api
category: Tickler
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016-2021 Tom Sydney Kerckhove'
license: AllRightsReserved
github: NorfairKing/tickler
default-extensions:
- NoImplicitPrelude

library:
  source-dirs: src
  ghc-options: -Wall

  dependencies:
  - QuickCheck
  - base >=4.7 && <5
  - bytestring
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-mergeful
  - genvalidity-text
  - genvalidity-time
  - genvalidity-typed-uuid
  - genvalidity-uuid
  - intray-data-gen
  - text
  - tickler-api
  - tickler-data
  - tickler-data-gen
  - validity
  - validity-bytestring
  - validity-text
  - validity-time

tests:
  tickler-api-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - base
    - bytestring
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-text
    - sydtest
    - text
    - tickler-api
    - tickler-api-gen
    - tickler-data
    - tickler-data-gen
