name: tickler-data

default-extensions:
- NoImplicitPrelude

library:
  source-dirs: src
  ghc-options: -Wall

  dependencies:
  - aeson
  - autodocodec
  - base >=4.7 && <5
  - base16-bytestring
  - bcrypt
  - bytestring
  - hashable
  - http-api-data
  - intray-data
  - path-pieces
  - persistent
  - persistent-template
  - random
  - servant-client-core
  - text
  - time
  - typed-uuid
  - validity
  - validity-bytestring
  - validity-text
  - validity-time
  - validity-uuid
